### ISSUE TITLE
Ghost Nitrogen

### ISSUE THREAD

**Issue by Toranks** [steamp0rt/Kerbalism#123]
I'm on the moon with a greenhouse, and no recycler of water or waste. When I have the Kerbal in EVA, the nitrogen consumption goes up, when I enter IVA, it is considerably reduced.

![image](https://user-images.githubusercontent.com/40789364/42458650-73892b84-839a-11e8-86ae-78a5454583fb.png)
![image](https://user-images.githubusercontent.com/40789364/42458728-992cd048-839a-11e8-84b6-52b0e04ac803.png)

**Comment by PiezPiedPy** [comment]
@Toranks A Kerbal uses volume in the craft mainly due to their fat belly's from all the snacks they eat, so when they go EVA they leave a deficit of pressure inside the craft that the pressure control will start to fill up using Nitrogen to bring the pressure back up to normal. Usually pressure control is only using Nitrogen for leaks which is why you see a small amount of Nitrogen being used all the time but when the pressure drops for what ever reason the pressure control will kick in at full and use a lot more Nitrogen until pressure is normal again.
Give the pressure control a few minuets to re-pressurize the craft and you should see the Nitrogen consumption drop to normal levels.

**Comment by Gordon-Dry** [comment]
I guess was @PiezPiedPy wanted to say it's the airlock loss.

But, how about a part upgrade, so that an airlock does not just let all the air flush out but uses pumps to gather it - and so lowering pressure in the airlock.
Then only a little will be lost.

**Comment by PiezPiedPy** [comment]
@Gordon-Dry nope, only the volume a Kerbal's fat ass (300cm^3) takes up is lost 😛 and in a mk1 pod its nearly half its volume (they need a nutritionist at that KSC).

Pods have a magic airlock, an airlock part would be good though.

**Comment by Toranks** [comment]
Thanks! Mistery resolved. The button has the message "venting" while it is done

**Comment by PiezPiedPy** [comment]
I feel another change coming up, I think it would be better if the button was changed to say pressurizing when re-pressurizing and venting when loosing pressure.
Inflatable Habitats have that functionality but they say inflating when building pressure.
