### ISSUE TITLE
Toggling anything with a click on a word in a Kerbalism UI needs pixel exact clicking

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#26]
I'm talking about the Tracking Station rendering.

I would prefer it if clicking anywhere on the red/green word would toggle.

**Comment by HaullyGames** [comment]
Hi @steamp0rt ,
I don't think it is a bug, but it is how we created the Panel using the "GUILayout.Label".

Please change it to "Enhancement" and assign to me.

Note: This change will affect all functions that use Panel, improvement the player interaction with the Kerbalism Panel system:
sample  
- Automatic will be easier to use, since you can click anywhere on the word "deployed | retracted" to call the toggle.
- Any Monitor that has a clickable label with toggle will be more precise.

**Comment by HaullyGames** [comment]
@Gordon-Dry 
The issue title should be more generic, it won't affect only the panel in Tracking Station.

**Comment by HaullyGames** [comment]
Talking about the fps issue that you have, I see this issue only when I used your GameData, I don't know which of those over 200 mods is causing the fds dropping.

I will test it again to see if it is related to Kerbalism, but in my test with RemoteTech + Kerbalism + BDB + CRP, no fps dropping in Tracking station.

**Comment by HaullyGames** [comment]
https://github.com/HaullyGames/Kerbalism_Shared/commit/5328b19b3ea1d95b3cece3cca1ff5930e2ce74c0

**Comment by HaullyGames** [comment]
PR - https://github.com/steamp0rt/Kerbalism/pull/252

**Comment by Gordon-Dry** [comment]
Jep
