### ISSUE TITLE
Reminder: transmission of data locked to 64k

### ISSUE THREAD

**Issue by Gordon-Dry** [steamp0rt/Kerbalism#28]
This is an old issue, mentioned here and there in the forums, but I decideed to put it here not to be forgotten.

When transmitting science data it's always 64 Kb/s transmission speed, no matter antenna type or distance.

**Comment by PiezPiedPy** [comment]
While looking at the problem with issue #29 I may have found the culprit to this, seems the cache is being continually initialized rather than just updating.

I'll look into it after I fix issue #29.

This cache thrashing may also be the cause of performance issues, such as in issue #27.

**Comment by Gordon-Dry** [comment]
That would be a win-win ...

**Comment by Gordon-Dry** [comment]
Using the private build of PiezPiedBy there is some improvement - the transmission rate changes depending the signal strength.
But the upper limit is still 64 Kb/s.

**Comment by PiezPiedPy** [comment]
still not looked at this yet 😉

**Comment by Gordon-Dry** [comment]
After fixing this, I have two suggestions for the next step:

1.
To avoid that a high gain transmission is sucking out all EC too fast, the transmission speed could be throttled down.
Either manually or better; automatically by just checking the EC input speed (solar panels, reactors etc.) and then throttling down the transmission speed that it needs slighly less EC to not make the total EC decrease too fast.
Because the total amount of Kb to be transmitted is known, the transmission speed could be calculated so that after the transmission is done with the currect EC input/output ratio of the whole vessel, the remaining EC is above a set threshold, like 50%.
This also means that the transmission speed should not be calculated once before transmission starts, but let's say once a second to dynamically fit the actual EC input/output ratio of the whole vessel.

2.
And another suggestion:
The transmission could also be toggleable by script like other modules can, so like to be set to pause the transmission when EC is low and resume transmission when EC is high again.


These two suggestions would be two different strategies, so the player would decide which one to choose.

Or you do, but then I suggest method 1.

**Comment by Gordon-Dry** [comment]
Regarding https://github.com/steamp0rt/Kerbalism/pull/42#issuecomment-394181439

How can these configs be done?

Just by MM patching or is it something else that has to be coded?

**Comment by PiezPiedPy** [comment]
Before Signals where removed there used to be a rate parameter in the antennas module, in case that parameter was missing there was a default of 64Kb which is the bit of code in the comment.
TBH Signals has not been removed fully and there are still remnants left behind such as the defaults for missing rate, ec cost etc.
What needs to be done is a rate parameter or something similar added to the transmitter modules of parts because the way things are at the moment all transmitters have the default rate fixed to them because they have no rate parameter.
I'll go through things and tidy up any left behind bits from signals then have a think about how to best implement a rate and ec cost scenario.

**Comment by PiezPiedPy** [comment]
been looking at the ModuleDataTransmitter and there is a PacketSize, PacketInterval (Bandwidth) and PacketResourceCost (EC)

Bandwidth can be used for the max ideal data rate, since it is in Mbits/sec it will have to be converted to Kbytes/sec in code (not a big issue, need to divide by 8 to get Bytes/sec and then divide by 1024 for Kbytes/s) e.g. 1Mit/s = 122Kb/s

EC rates are ridiculously high the smallest stock antenna uses 12ec/packet = 20ec/sec or 20KW/s (Wow). 

Transmission with the ISS uses 20-100W combined, the HAM radio onboard the ISS has a max power of 25W and usually uses 10W for comms with HAM operators. Voyager 1 uses 22.5W Voyager 2 and New Horizons use 20W, a typical weather satellite uses 5-10W, these examples are just to give an idea of power requirements.

With this information I'm going to drastically reduce the EC requirements on the stock antennas and command modules/pods basically by 1000 times (20KW/s will be 20W/s) seems more reasonable.

**Comment by Gordon-Dry** [comment]
I guess this is because there is no common knowledge transported from SQUAD to mod devs and to palyers what 1 EC/s in the beginning.

So some modders just decided what it is on themselves.

Later then some forum posts came up in which a comprehensive common sense of what 1 EC is was to pinpoint.

So I guess it's simple like that; some folks think 1 EC/s represents 1 W/s, others say it's 1 kW/s.

This of course makes things complicated.

I never understood why my probes or manned pods need batteries that would be enough for 100 Tesla S to move from San Fransico to Miami Beach with state patrollers tailing just to survive the shadow ride of an orbit.

The huge amount of EC to be used for data transmissions by stock is one of the reasons.
The massively overpowered but also unrealistic non-saturated reaction wheels are another reason.

**Comment by PiezPiedPy** [comment]
Absolutely agree

**Comment by Gordon-Dry** [comment]
I just created a small patch for my own use as an intermediate solution - avoiding huge amounts of batteries and massively oversized solar panels on small probes that go flyby a planet:
```
// PiezPiedBy said at https://github.com/steamp0rt/Kerbalism/issues/28#issuecomment-394465642
//
// EC rates are ridiculously high the smallest stock antenna uses 12ec/packet = 20ec/sec or 20KW/s (Wow).
//
// Transmission with the ISS uses 20-100W combined, the HAM radio onboard the ISS has a max power of 25W and usually uses 10W for comms with HAM operators.
// Voyager 1 uses 22.5W Voyager 2 and New Horizons use 20W, a typical weather satellite uses 5-10W, these examples are just to give an idea of power requirements.
//
// With this information I'm going to drastically reduce the EC requirements on all ModuleDataTransmitter modules basically by 1000 times (20KW/s will be 20W/s) seems more reasonable.
//
//
// So I decided to create this small patch meanwhile
//
// Gordon Dry

// I will add NEEDS[!Kerbalism] later when it's ready
@PART[*]:HAS[@Module[ModuleDataTransmitter]]:FINAL
{
	@description ^= :$: <color=orange>Needs 1000x less EC than stock, because that is totally unrealistically high.</color> :
	@Module[ModuleDataTransmitter]
	{
		@packetResourceCost /= 1000
	}
}
```
;-)

**Comment by PiezPiedPy** [comment]
Got too be faster than that Gordon 😛 
Gona sort the data rates next

**Comment by Gordon-Dry** [comment]
It works in the test build, so I just close it now.

Also the phantom EC bug is gone by MM patch, see https://github.com/steamp0rt/Kerbalism/issues/53
