### ISSUE TITLE
Missing monoprop on EVA for some kerbals

### ISSUE THREAD

**Issue by dymanoid** [steamp0rt/Kerbalism#282]
This is a weird bug. If you have an idea how to fix it, I could try to submit a pull request.

**Issue:**
On exiting a vessel for EVA, **some** kerbals are missing the monoprop from Kerbalism's point of view. So jetpacks won't work. However, the game shows the full monoprop storage for the kerbal.

**My findings:**

The method `Callbacks.ToEVA` sets up the resources for EVA.
However, I noticed that for some kerbals the `data.to.Resources` collection doesn't contain monoprop at all. So, Kerbalism doesn't apply monoprop and thinks that this poor kerbal cannot use the jetpack.

However, the game **adds** some monoprop to that kerbal after this callback `ToEVA` returns, and in particular in the `KerbalEVA.OnStart` method which is called asynchronously as a coroutine. Thus, the monoprop resource is added **after** Kerbalism sets up EVA. That's the explanation why the game shows full monoprop while Kerbalism thinks there's none.

This is what I found in the `KerbalEVA.OnStart` method:

    if (!part.Resources.Contains(propellantResourceName))
    {
        part.Resources.Add(
            propellantResourceName,
            propellantResourceDefaultAmount,
            propellantResourceDefaultAmount,
            true,
            false,
            false,
            true, PartResource.FlowMode.Both);
    }

(E.g. inspecting the `Resources` collection **after** an EVA in the `Callbacks.FromEVA` method shows that the monoprop is there.)

Any idea how to fix this?

**Comment by SirMortimer** [comment]
I think I just did. While looking at #288 I noticed the same that you observed, monoprop wasn't in `data.to.Resources` at the time and KSP added it later. Somehow.

So instead of fighting KSB about those 5 units of monoprop, I set an internal variable to the desired amount of monoprop that should be on the kerbal, let KSP add all 5 units so it is happy and then set the correct amount of monoprop on the first simulation tick. It should be fixed with PR #343

**Comment by lordcirth** [comment]
If I understand correctly, this patch lets KSP move MP from the ship to the Kerbal, then reads how much the Kerbal has?

**Comment by SirMortimer** [comment]
This patch calculates how much a Kerbal should have after leaving the vessel, anything from 0 to 5 units. that amount is removed from the ship immediately, but not added to the EVA because of the reasons described above. then it will let KSP initialize the Eva, and on the next simulation tick it will set the correct amount of monoprop.

@dymanoid yes, it fixes that. there is no more magical monoprop appearing out of nothing.

**Comment by twisted-biscuit** [comment]
I installed this patch to try fix the the EVA monoprop issue, but now it looks like there's a problem with the duration reporting. I have very basic life support on my vessel, but the duration of all resources is "perpetual", both in the VAB and on the launchpad. Two screengrabs attached.

![Screenshot_3](https://user-images.githubusercontent.com/48832447/54828556-5a9f8380-4cac-11e9-851d-e0872cfc5a9f.png)
![Screenshot_4](https://user-images.githubusercontent.com/48832447/54828557-5a9f8380-4cac-11e9-8959-e49f9aa636b9.png)

**Comment by lordcirth** [comment]
Can you also post screenshots of the craft in VAB and launchpad? Thanks.

**Comment by twisted-biscuit** [comment]
Sorry, should have specified: first photo is of the ship in the VAB, bottom photo is the ship on the pad. Or did you want to see the whole ship in the frame?

**Comment by twisted-biscuit** [comment]
This may have been a red herring. I reinstalled the mod and created a new ship in the VAB and now everything seems okay. Will notify if I see anything else strange.

**Comment by lordcirth** [comment]
I meant screenshots of the whole ship, yes. To see what parts and crew you had. But if it's working now, that's fine. It may have been leftover state from the previous version attached to the craft.

**Comment by steamp0rt** [comment]
fixed in 3.0
