### ISSUE TITLE
Energy generation is completely ignored

### ISSUE THREAD

**Issue by the-emerald** [steamp0rt/Kerbalism#318]
For some reason, any generation of electricity is completely ignored (including nuclear reactors from Near Future Electrical, stock solar panels, and RTGs). This causes some obvious issues to the wellbeing of Kerbals and probes alike. The first image attached suggests that #305 is also happening. I'm running Kerbalism v2.1.2

![kerbal space program 2019-02-13 7_59_40 pm](https://user-images.githubusercontent.com/12746683/52740149-522b9d00-2fca-11e9-9a91-673b5884e3ee.png)
![kerbal space program 2019-02-13 7_52_38 pm](https://user-images.githubusercontent.com/12746683/52740150-52c43380-2fca-11e9-9ec1-0912de2d3e52.png)
![kerbal space program 2019-02-13 7_54_43 pm](https://user-images.githubusercontent.com/12746683/52740151-52c43380-2fca-11e9-9fba-8181752b49f7.png)

**Comment by lordcirth** [comment]
Some clarifying questions:

- KSP version?
- Installed Kerbalism from CKAN or manually?
- What MM version?
- What CRP version?

**Comment by the-emerald** [comment]
- I'm on KSP v1.4.5
- All mods are installed manually.
- MM v.3.0.7
- CRP is `MAJOR 0, MINOR 10, PATCH 0` according to `CRP.version`

**Comment by the-emerald** [comment]
Side note: reverting to Kerbalism v.1.8.0 fixes the issue (and #305 as well)

**Comment by steamp0rt** [comment]
Post a `KSP.log` from a session where the issue is obviously present

**Comment by the-emerald** [comment]
[Here's the log.](https://gist.github.com/the-emerald/518edd289744389dc4ff540e368ac186)

I loaded into the game and then switched to a probe where the issue is present. Then I timewarped for a couple of seconds.

**Comment by PiezPiedPy** [comment]
I think this might be something to do with changes that @madman2003 made to the NearFuture support file 🤔

**Comment by madman2003** [comment]
It’s been a while since I played, so I’m doing this from memory. The most suspicious and easy to look into thing is the solar panels not working. They have independent code for power generation. I doubt stock ksp + ketbalism has they broken. So start from there and figure out which mod breaks solar panels.

For the reactors it’s worthwhile to use a debug build of kerbalism to see the pseudo resources that control the reactor process. It is possible that Near future electrical changed the modules on there part, most of the  NF-E custom stuff is completely removed by kerbalism, because kerbalism has its own resource simulator.

**Comment by PiezPiedPy** [comment]
@madman2003 thanks 😉 having a look see what I can find, not used NearFuture's stuff

**Comment by the-emerald** [comment]
@PiezPiedPy [ModuleManager.log](https://gist.github.com/the-emerald/18795a8dc7ee14db189c07f97087a407) as requested...

**Comment by the-emerald** [comment]
Looks like by removing Kerbal Planetary Base Systems the power generation works again.
