### ISSUE TITLE
Can't use symetry modes greater than 2 on some parts

### ISSUE THREAD

**Issue by bartekkru100** [steamp0rt/Kerbalism#375]
While trying to apply 4x symetry to pressurised tanks I've noticed than that it doesn't let me attach it. 
![image](https://user-images.githubusercontent.com/9304355/55691160-7046c580-599b-11e9-8e1a-0cebea963d8e.png)
I use Editor Extensions Redux that allows more symetry options, might be a comptibility issue.

**Comment by Rockstar04** [comment]
I have had the exact same issue, and also have EER.

**Comment by UsernamesAreAlwaysTaken** [comment]
That's not EEX, that's an issue with a module in the parts you're trying to place (the one that handles resource swaps for the tanks). It'll either get fixed, or nuked in 2.2

**Comment by SirMortimer** [comment]
This affects all parts with modules that dynamically add or remove resources. Currently these are Configure, Habitat and ProcessController. You won't be able to place ECLSS units, Pods, Fuel Tanks and any 3rd party mod part in symmetry groups.

While I could live with a limitation to being able to use more than 2 parts in symmetry, there is this nagging suspicion that this will come to haunt us if it isn't taken care of properly.

At first I thought the problem was with the Configure module, but it isn't. The problem is with the way we dynamically add and remove resources to a part in the editor. There is some serialization magic going on within the Unity framework, stuff I never wanted to look at but now have to.

**Comment by SirMortimer** [comment]
I think I found a solution.
